/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmNotInStock implements Serializable {

	private static final long serialVersionUID = -720973324;

	private Integer pFilmCount;

	public FilmNotInStock() {}

	public FilmNotInStock(FilmNotInStock value) {
		this.pFilmCount = value.pFilmCount;
	}

	public FilmNotInStock(
		Integer pFilmCount
	) {
		this.pFilmCount = pFilmCount;
	}

	public Integer getPFilmCount() {
		return this.pFilmCount;
	}

	public void setPFilmCount(Integer pFilmCount) {
		this.pFilmCount = pFilmCount;
	}
}
