/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmActor implements Serializable {

	private static final long serialVersionUID = -1140692675;

	private Short     actorId;
	private Short     filmId;
	private Timestamp lastUpdate;

	public FilmActor() {}

	public FilmActor(FilmActor value) {
		this.actorId = value.actorId;
		this.filmId = value.filmId;
		this.lastUpdate = value.lastUpdate;
	}

	public FilmActor(
		Short     actorId,
		Short     filmId,
		Timestamp lastUpdate
	) {
		this.actorId = actorId;
		this.filmId = filmId;
		this.lastUpdate = lastUpdate;
	}

	public Short getActorId() {
		return this.actorId;
	}

	public void setActorId(Short actorId) {
		this.actorId = actorId;
	}

	public Short getFilmId() {
		return this.filmId;
	}

	public void setFilmId(Short filmId) {
		this.filmId = filmId;
	}

	public Timestamp getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
}
