/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmCategory implements Serializable {

	private static final long serialVersionUID = 365084790;

	private Short     filmId;
	private Short     categoryId;
	private Timestamp lastUpdate;

	public FilmCategory() {}

	public FilmCategory(FilmCategory value) {
		this.filmId = value.filmId;
		this.categoryId = value.categoryId;
		this.lastUpdate = value.lastUpdate;
	}

	public FilmCategory(
		Short     filmId,
		Short     categoryId,
		Timestamp lastUpdate
	) {
		this.filmId = filmId;
		this.categoryId = categoryId;
		this.lastUpdate = lastUpdate;
	}

	public Short getFilmId() {
		return this.filmId;
	}

	public void setFilmId(Short filmId) {
		this.filmId = filmId;
	}

	public Short getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Short categoryId) {
		this.categoryId = categoryId;
	}

	public Timestamp getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
}
