/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoricoRentas implements Serializable {

	private static final long serialVersionUID = -867912853;

	private Short     customerId;
	private Timestamp previousDate;
	private Timestamp rentalDate;
	private Long      howMany;
	private Timestamp nextDate;

	public HistoricoRentas() {}

	public HistoricoRentas(HistoricoRentas value) {
		this.customerId = value.customerId;
		this.previousDate = value.previousDate;
		this.rentalDate = value.rentalDate;
		this.howMany = value.howMany;
		this.nextDate = value.nextDate;
	}

	public HistoricoRentas(
		Short     customerId,
		Timestamp previousDate,
		Timestamp rentalDate,
		Long      howMany,
		Timestamp nextDate
	) {
		this.customerId = customerId;
		this.previousDate = previousDate;
		this.rentalDate = rentalDate;
		this.howMany = howMany;
		this.nextDate = nextDate;
	}

	public Short getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Short customerId) {
		this.customerId = customerId;
	}

	public Timestamp getPreviousDate() {
		return this.previousDate;
	}

	public void setPreviousDate(Timestamp previousDate) {
		this.previousDate = previousDate;
	}

	public Timestamp getRentalDate() {
		return this.rentalDate;
	}

	public void setRentalDate(Timestamp rentalDate) {
		this.rentalDate = rentalDate;
	}

	public Long getHowMany() {
		return this.howMany;
	}

	public void setHowMany(Long howMany) {
		this.howMany = howMany;
	}

	public Timestamp getNextDate() {
		return this.nextDate;
	}

	public void setNextDate(Timestamp nextDate) {
		this.nextDate = nextDate;
	}
}
