/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.enums;


import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Public;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum MpaaRating implements EnumType {

	G("G"),

	PG("PG"),

	PG_13("PG-13"),

	R("R"),

	NC_17("NC-17");

	private final String literal;

	private MpaaRating(String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return Public.PUBLIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		return "mpaa_rating";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getLiteral() {
		return literal;
	}
}
