/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.routines;


import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LastUpdated extends AbstractRoutine<Object> {

	private static final long serialVersionUID = 246886848;

	/**
	 * The parameter <code>public.last_updated.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false);

	/**
	 * Create a new routine call instance
	 */
	public LastUpdated() {
		super("last_updated", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

		setReturnParameter(RETURN_VALUE);
	}
}
