/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables.records;


import javax.annotation.Generated;

import mx.ihsa.videoclub.model.tables.ActorInfo;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorInfoRecord extends TableRecordImpl<ActorInfoRecord> implements Record4<Integer, String, String, String> {

	private static final long serialVersionUID = 1434624941;

	/**
	 * Setter for <code>public.actor_info.actor_id</code>.
	 */
	public void setActorId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.actor_info.actor_id</code>.
	 */
	public Integer getActorId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.actor_info.first_name</code>.
	 */
	public void setFirstName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.actor_info.first_name</code>.
	 */
	public String getFirstName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.actor_info.last_name</code>.
	 */
	public void setLastName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.actor_info.last_name</code>.
	 */
	public String getLastName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.actor_info.film_info</code>.
	 */
	public void setFilmInfo(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.actor_info.film_info</code>.
	 */
	public String getFilmInfo() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ActorInfo.ACTOR_INFO.ACTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ActorInfo.ACTOR_INFO.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return ActorInfo.ACTOR_INFO.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return ActorInfo.ACTOR_INFO.FILM_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getActorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getFilmInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorInfoRecord value1(Integer value) {
		setActorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorInfoRecord value2(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorInfoRecord value3(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorInfoRecord value4(String value) {
		setFilmInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActorInfoRecord values(Integer value1, String value2, String value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActorInfoRecord
	 */
	public ActorInfoRecord() {
		super(ActorInfo.ACTOR_INFO);
	}

	/**
	 * Create a detached, initialised ActorInfoRecord
	 */
	public ActorInfoRecord(Integer actorId, String firstName, String lastName, String filmInfo) {
		super(ActorInfo.ACTOR_INFO);

		setValue(0, actorId);
		setValue(1, firstName);
		setValue(2, lastName);
		setValue(3, filmInfo);
	}
}
