/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables.records;


import javax.annotation.Generated;

import mx.ihsa.videoclub.model.tables.CustomerList;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerListRecord extends TableRecordImpl<CustomerListRecord> implements Record9<Integer, String, String, String, String, String, String, String, Short> {

	private static final long serialVersionUID = -166878160;

	/**
	 * Setter for <code>public.customer_list.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.customer_list.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.customer_list.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.customer_list.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.customer_list.address</code>.
	 */
	public void setAddress(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.customer_list.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.customer_list.zip code</code>.
	 */
	public void setZip_code(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.customer_list.zip code</code>.
	 */
	public String getZip_code() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.customer_list.phone</code>.
	 */
	public void setPhone(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.customer_list.phone</code>.
	 */
	public String getPhone() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.customer_list.city</code>.
	 */
	public void setCity(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.customer_list.city</code>.
	 */
	public String getCity() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.customer_list.country</code>.
	 */
	public void setCountry(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.customer_list.country</code>.
	 */
	public String getCountry() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.customer_list.notes</code>.
	 */
	public void setNotes(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.customer_list.notes</code>.
	 */
	public String getNotes() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.customer_list.sid</code>.
	 */
	public void setSid(Short value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.customer_list.sid</code>.
	 */
	public Short getSid() {
		return (Short) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, String, String, String, String, String, String, Short> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, String, String, String, String, String, String, Short> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CustomerList.CUSTOMER_LIST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return CustomerList.CUSTOMER_LIST.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CustomerList.CUSTOMER_LIST.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return CustomerList.CUSTOMER_LIST.ZIP_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return CustomerList.CUSTOMER_LIST.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return CustomerList.CUSTOMER_LIST.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return CustomerList.CUSTOMER_LIST.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return CustomerList.CUSTOMER_LIST.NOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field9() {
		return CustomerList.CUSTOMER_LIST.SID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getZip_code();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getNotes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value9() {
		return getSid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value3(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value4(String value) {
		setZip_code(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value5(String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value6(String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value7(String value) {
		setCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value8(String value) {
		setNotes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord value9(Short value) {
		setSid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CustomerListRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Short value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CustomerListRecord
	 */
	public CustomerListRecord() {
		super(CustomerList.CUSTOMER_LIST);
	}

	/**
	 * Create a detached, initialised CustomerListRecord
	 */
	public CustomerListRecord(Integer id, String name, String address, String zip_code, String phone, String city, String country, String notes, Short sid) {
		super(CustomerList.CUSTOMER_LIST);

		setValue(0, id);
		setValue(1, name);
		setValue(2, address);
		setValue(3, zip_code);
		setValue(4, phone);
		setValue(5, city);
		setValue(6, country);
		setValue(7, notes);
		setValue(8, sid);
	}
}
