/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import mx.ihsa.videoclub.model.tables.Rental;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalRecord extends UpdatableRecordImpl<RentalRecord> implements Record7<Integer, Timestamp, Integer, Short, Timestamp, Short, Timestamp> {

	private static final long serialVersionUID = 1096828062;

	/**
	 * Setter for <code>public.rental.rental_id</code>.
	 */
	public void setRentalId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.rental.rental_id</code>.
	 */
	public Integer getRentalId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.rental.rental_date</code>.
	 */
	public void setRentalDate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.rental.rental_date</code>.
	 */
	public Timestamp getRentalDate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>public.rental.inventory_id</code>.
	 */
	public void setInventoryId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.rental.inventory_id</code>.
	 */
	public Integer getInventoryId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.rental.customer_id</code>.
	 */
	public void setCustomerId(Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.rental.customer_id</code>.
	 */
	public Short getCustomerId() {
		return (Short) getValue(3);
	}

	/**
	 * Setter for <code>public.rental.return_date</code>.
	 */
	public void setReturnDate(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.rental.return_date</code>.
	 */
	public Timestamp getReturnDate() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.rental.staff_id</code>.
	 */
	public void setStaffId(Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.rental.staff_id</code>.
	 */
	public Short getStaffId() {
		return (Short) getValue(5);
	}

	/**
	 * Setter for <code>public.rental.last_update</code>.
	 */
	public void setLastUpdate(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.rental.last_update</code>.
	 */
	public Timestamp getLastUpdate() {
		return (Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Timestamp, Integer, Short, Timestamp, Short, Timestamp> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Timestamp, Integer, Short, Timestamp, Short, Timestamp> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Rental.RENTAL.RENTAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Rental.RENTAL.RENTAL_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Rental.RENTAL.INVENTORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field4() {
		return Rental.RENTAL.CUSTOMER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Rental.RENTAL.RETURN_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field6() {
		return Rental.RENTAL.STAFF_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Rental.RENTAL.LAST_UPDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRentalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getRentalDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getInventoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value4() {
		return getCustomerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getReturnDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value6() {
		return getStaffId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getLastUpdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord value1(Integer value) {
		setRentalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord value2(Timestamp value) {
		setRentalDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord value3(Integer value) {
		setInventoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord value4(Short value) {
		setCustomerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord value5(Timestamp value) {
		setReturnDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord value6(Short value) {
		setStaffId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord value7(Timestamp value) {
		setLastUpdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RentalRecord values(Integer value1, Timestamp value2, Integer value3, Short value4, Timestamp value5, Short value6, Timestamp value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RentalRecord
	 */
	public RentalRecord() {
		super(Rental.RENTAL);
	}

	/**
	 * Create a detached, initialised RentalRecord
	 */
	public RentalRecord(Integer rentalId, Timestamp rentalDate, Integer inventoryId, Short customerId, Timestamp returnDate, Short staffId, Timestamp lastUpdate) {
		super(Rental.RENTAL);

		setValue(0, rentalId);
		setValue(1, rentalDate);
		setValue(2, inventoryId);
		setValue(3, customerId);
		setValue(4, returnDate);
		setValue(5, staffId);
		setValue(6, lastUpdate);
	}
}
