/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model;


import javax.annotation.Generated;

import mx.ihsa.videoclub.model.tables.Actor;
import mx.ihsa.videoclub.model.tables.Address;
import mx.ihsa.videoclub.model.tables.Category;
import mx.ihsa.videoclub.model.tables.City;
import mx.ihsa.videoclub.model.tables.Country;
import mx.ihsa.videoclub.model.tables.Customer;
import mx.ihsa.videoclub.model.tables.Film;
import mx.ihsa.videoclub.model.tables.FilmActor;
import mx.ihsa.videoclub.model.tables.FilmCategory;
import mx.ihsa.videoclub.model.tables.Inventory;
import mx.ihsa.videoclub.model.tables.Language;
import mx.ihsa.videoclub.model.tables.Payment;
import mx.ihsa.videoclub.model.tables.PaymentP2007_01;
import mx.ihsa.videoclub.model.tables.PaymentP2007_02;
import mx.ihsa.videoclub.model.tables.PaymentP2007_03;
import mx.ihsa.videoclub.model.tables.PaymentP2007_04;
import mx.ihsa.videoclub.model.tables.PaymentP2007_05;
import mx.ihsa.videoclub.model.tables.PaymentP2007_06;
import mx.ihsa.videoclub.model.tables.Rental;
import mx.ihsa.videoclub.model.tables.RewardsReport;
import mx.ihsa.videoclub.model.tables.Staff;
import mx.ihsa.videoclub.model.tables.Store;
import mx.ihsa.videoclub.model.tables.records.ActorRecord;
import mx.ihsa.videoclub.model.tables.records.AddressRecord;
import mx.ihsa.videoclub.model.tables.records.CategoryRecord;
import mx.ihsa.videoclub.model.tables.records.CityRecord;
import mx.ihsa.videoclub.model.tables.records.CountryRecord;
import mx.ihsa.videoclub.model.tables.records.CustomerRecord;
import mx.ihsa.videoclub.model.tables.records.FilmActorRecord;
import mx.ihsa.videoclub.model.tables.records.FilmCategoryRecord;
import mx.ihsa.videoclub.model.tables.records.FilmRecord;
import mx.ihsa.videoclub.model.tables.records.InventoryRecord;
import mx.ihsa.videoclub.model.tables.records.LanguageRecord;
import mx.ihsa.videoclub.model.tables.records.PaymentP2007_01Record;
import mx.ihsa.videoclub.model.tables.records.PaymentP2007_02Record;
import mx.ihsa.videoclub.model.tables.records.PaymentP2007_03Record;
import mx.ihsa.videoclub.model.tables.records.PaymentP2007_04Record;
import mx.ihsa.videoclub.model.tables.records.PaymentP2007_05Record;
import mx.ihsa.videoclub.model.tables.records.PaymentP2007_06Record;
import mx.ihsa.videoclub.model.tables.records.PaymentRecord;
import mx.ihsa.videoclub.model.tables.records.RentalRecord;
import mx.ihsa.videoclub.model.tables.records.RewardsReportRecord;
import mx.ihsa.videoclub.model.tables.records.StaffRecord;
import mx.ihsa.videoclub.model.tables.records.StoreRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<ActorRecord, Integer> IDENTITY_ACTOR = Identities0.IDENTITY_ACTOR;
	public static final Identity<AddressRecord, Integer> IDENTITY_ADDRESS = Identities0.IDENTITY_ADDRESS;
	public static final Identity<CategoryRecord, Integer> IDENTITY_CATEGORY = Identities0.IDENTITY_CATEGORY;
	public static final Identity<CityRecord, Integer> IDENTITY_CITY = Identities0.IDENTITY_CITY;
	public static final Identity<CountryRecord, Integer> IDENTITY_COUNTRY = Identities0.IDENTITY_COUNTRY;
	public static final Identity<CustomerRecord, Integer> IDENTITY_CUSTOMER = Identities0.IDENTITY_CUSTOMER;
	public static final Identity<FilmRecord, Integer> IDENTITY_FILM = Identities0.IDENTITY_FILM;
	public static final Identity<InventoryRecord, Integer> IDENTITY_INVENTORY = Identities0.IDENTITY_INVENTORY;
	public static final Identity<LanguageRecord, Integer> IDENTITY_LANGUAGE = Identities0.IDENTITY_LANGUAGE;
	public static final Identity<PaymentRecord, Integer> IDENTITY_PAYMENT = Identities0.IDENTITY_PAYMENT;
	public static final Identity<PaymentP2007_01Record, Integer> IDENTITY_PAYMENT_P2007_01 = Identities0.IDENTITY_PAYMENT_P2007_01;
	public static final Identity<PaymentP2007_02Record, Integer> IDENTITY_PAYMENT_P2007_02 = Identities0.IDENTITY_PAYMENT_P2007_02;
	public static final Identity<PaymentP2007_03Record, Integer> IDENTITY_PAYMENT_P2007_03 = Identities0.IDENTITY_PAYMENT_P2007_03;
	public static final Identity<PaymentP2007_04Record, Integer> IDENTITY_PAYMENT_P2007_04 = Identities0.IDENTITY_PAYMENT_P2007_04;
	public static final Identity<PaymentP2007_05Record, Integer> IDENTITY_PAYMENT_P2007_05 = Identities0.IDENTITY_PAYMENT_P2007_05;
	public static final Identity<PaymentP2007_06Record, Integer> IDENTITY_PAYMENT_P2007_06 = Identities0.IDENTITY_PAYMENT_P2007_06;
	public static final Identity<RentalRecord, Integer> IDENTITY_RENTAL = Identities0.IDENTITY_RENTAL;
	public static final Identity<RewardsReportRecord, Integer> IDENTITY_REWARDS_REPORT = Identities0.IDENTITY_REWARDS_REPORT;
	public static final Identity<StaffRecord, Integer> IDENTITY_STAFF = Identities0.IDENTITY_STAFF;
	public static final Identity<StoreRecord, Integer> IDENTITY_STORE = Identities0.IDENTITY_STORE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<ActorRecord> ACTOR_PKEY = UniqueKeys0.ACTOR_PKEY;
	public static final UniqueKey<AddressRecord> ADDRESS_PKEY = UniqueKeys0.ADDRESS_PKEY;
	public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = UniqueKeys0.CATEGORY_PKEY;
	public static final UniqueKey<CityRecord> CITY_PKEY = UniqueKeys0.CITY_PKEY;
	public static final UniqueKey<CountryRecord> COUNTRY_PKEY = UniqueKeys0.COUNTRY_PKEY;
	public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = UniqueKeys0.CUSTOMER_PKEY;
	public static final UniqueKey<FilmRecord> FILM_PKEY = UniqueKeys0.FILM_PKEY;
	public static final UniqueKey<FilmActorRecord> FILM_ACTOR_PKEY = UniqueKeys0.FILM_ACTOR_PKEY;
	public static final UniqueKey<FilmCategoryRecord> FILM_CATEGORY_PKEY = UniqueKeys0.FILM_CATEGORY_PKEY;
	public static final UniqueKey<InventoryRecord> INVENTORY_PKEY = UniqueKeys0.INVENTORY_PKEY;
	public static final UniqueKey<LanguageRecord> LANGUAGE_PKEY = UniqueKeys0.LANGUAGE_PKEY;
	public static final UniqueKey<PaymentRecord> PAYMENT_PKEY = UniqueKeys0.PAYMENT_PKEY;
	public static final UniqueKey<RentalRecord> RENTAL_PKEY = UniqueKeys0.RENTAL_PKEY;
	public static final UniqueKey<StaffRecord> STAFF_PKEY = UniqueKeys0.STAFF_PKEY;
	public static final UniqueKey<StoreRecord> STORE_PKEY = UniqueKeys0.STORE_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AddressRecord, CityRecord> ADDRESS__ADDRESS_CITY_ID_FKEY = ForeignKeys0.ADDRESS__ADDRESS_CITY_ID_FKEY;
	public static final ForeignKey<CityRecord, CountryRecord> CITY__CITY_COUNTRY_ID_FKEY = ForeignKeys0.CITY__CITY_COUNTRY_ID_FKEY;
	public static final ForeignKey<CustomerRecord, StoreRecord> CUSTOMER__CUSTOMER_STORE_ID_FKEY = ForeignKeys0.CUSTOMER__CUSTOMER_STORE_ID_FKEY;
	public static final ForeignKey<CustomerRecord, AddressRecord> CUSTOMER__CUSTOMER_ADDRESS_ID_FKEY = ForeignKeys0.CUSTOMER__CUSTOMER_ADDRESS_ID_FKEY;
	public static final ForeignKey<FilmRecord, LanguageRecord> FILM__FILM_LANGUAGE_ID_FKEY = ForeignKeys0.FILM__FILM_LANGUAGE_ID_FKEY;
	public static final ForeignKey<FilmRecord, LanguageRecord> FILM__FILM_ORIGINAL_LANGUAGE_ID_FKEY = ForeignKeys0.FILM__FILM_ORIGINAL_LANGUAGE_ID_FKEY;
	public static final ForeignKey<FilmActorRecord, ActorRecord> FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY = ForeignKeys0.FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY;
	public static final ForeignKey<FilmActorRecord, FilmRecord> FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY = ForeignKeys0.FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY;
	public static final ForeignKey<FilmCategoryRecord, FilmRecord> FILM_CATEGORY__FILM_CATEGORY_FILM_ID_FKEY = ForeignKeys0.FILM_CATEGORY__FILM_CATEGORY_FILM_ID_FKEY;
	public static final ForeignKey<FilmCategoryRecord, CategoryRecord> FILM_CATEGORY__FILM_CATEGORY_CATEGORY_ID_FKEY = ForeignKeys0.FILM_CATEGORY__FILM_CATEGORY_CATEGORY_ID_FKEY;
	public static final ForeignKey<InventoryRecord, FilmRecord> INVENTORY__INVENTORY_FILM_ID_FKEY = ForeignKeys0.INVENTORY__INVENTORY_FILM_ID_FKEY;
	public static final ForeignKey<InventoryRecord, StoreRecord> INVENTORY__INVENTORY_STORE_ID_FKEY = ForeignKeys0.INVENTORY__INVENTORY_STORE_ID_FKEY;
	public static final ForeignKey<PaymentRecord, CustomerRecord> PAYMENT__PAYMENT_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT__PAYMENT_CUSTOMER_ID_FKEY;
	public static final ForeignKey<PaymentRecord, StaffRecord> PAYMENT__PAYMENT_STAFF_ID_FKEY = ForeignKeys0.PAYMENT__PAYMENT_STAFF_ID_FKEY;
	public static final ForeignKey<PaymentRecord, RentalRecord> PAYMENT__PAYMENT_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT__PAYMENT_RENTAL_ID_FKEY;
	public static final ForeignKey<PaymentP2007_01Record, CustomerRecord> PAYMENT_P2007_01__PAYMENT_P2007_01_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT_P2007_01__PAYMENT_P2007_01_CUSTOMER_ID_FKEY;
	public static final ForeignKey<PaymentP2007_01Record, StaffRecord> PAYMENT_P2007_01__PAYMENT_P2007_01_STAFF_ID_FKEY = ForeignKeys0.PAYMENT_P2007_01__PAYMENT_P2007_01_STAFF_ID_FKEY;
	public static final ForeignKey<PaymentP2007_01Record, RentalRecord> PAYMENT_P2007_01__PAYMENT_P2007_01_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT_P2007_01__PAYMENT_P2007_01_RENTAL_ID_FKEY;
	public static final ForeignKey<PaymentP2007_02Record, CustomerRecord> PAYMENT_P2007_02__PAYMENT_P2007_02_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT_P2007_02__PAYMENT_P2007_02_CUSTOMER_ID_FKEY;
	public static final ForeignKey<PaymentP2007_02Record, StaffRecord> PAYMENT_P2007_02__PAYMENT_P2007_02_STAFF_ID_FKEY = ForeignKeys0.PAYMENT_P2007_02__PAYMENT_P2007_02_STAFF_ID_FKEY;
	public static final ForeignKey<PaymentP2007_02Record, RentalRecord> PAYMENT_P2007_02__PAYMENT_P2007_02_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT_P2007_02__PAYMENT_P2007_02_RENTAL_ID_FKEY;
	public static final ForeignKey<PaymentP2007_03Record, CustomerRecord> PAYMENT_P2007_03__PAYMENT_P2007_03_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT_P2007_03__PAYMENT_P2007_03_CUSTOMER_ID_FKEY;
	public static final ForeignKey<PaymentP2007_03Record, StaffRecord> PAYMENT_P2007_03__PAYMENT_P2007_03_STAFF_ID_FKEY = ForeignKeys0.PAYMENT_P2007_03__PAYMENT_P2007_03_STAFF_ID_FKEY;
	public static final ForeignKey<PaymentP2007_03Record, RentalRecord> PAYMENT_P2007_03__PAYMENT_P2007_03_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT_P2007_03__PAYMENT_P2007_03_RENTAL_ID_FKEY;
	public static final ForeignKey<PaymentP2007_04Record, CustomerRecord> PAYMENT_P2007_04__PAYMENT_P2007_04_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT_P2007_04__PAYMENT_P2007_04_CUSTOMER_ID_FKEY;
	public static final ForeignKey<PaymentP2007_04Record, StaffRecord> PAYMENT_P2007_04__PAYMENT_P2007_04_STAFF_ID_FKEY = ForeignKeys0.PAYMENT_P2007_04__PAYMENT_P2007_04_STAFF_ID_FKEY;
	public static final ForeignKey<PaymentP2007_04Record, RentalRecord> PAYMENT_P2007_04__PAYMENT_P2007_04_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT_P2007_04__PAYMENT_P2007_04_RENTAL_ID_FKEY;
	public static final ForeignKey<PaymentP2007_05Record, CustomerRecord> PAYMENT_P2007_05__PAYMENT_P2007_05_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT_P2007_05__PAYMENT_P2007_05_CUSTOMER_ID_FKEY;
	public static final ForeignKey<PaymentP2007_05Record, StaffRecord> PAYMENT_P2007_05__PAYMENT_P2007_05_STAFF_ID_FKEY = ForeignKeys0.PAYMENT_P2007_05__PAYMENT_P2007_05_STAFF_ID_FKEY;
	public static final ForeignKey<PaymentP2007_05Record, RentalRecord> PAYMENT_P2007_05__PAYMENT_P2007_05_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT_P2007_05__PAYMENT_P2007_05_RENTAL_ID_FKEY;
	public static final ForeignKey<PaymentP2007_06Record, CustomerRecord> PAYMENT_P2007_06__PAYMENT_P2007_06_CUSTOMER_ID_FKEY = ForeignKeys0.PAYMENT_P2007_06__PAYMENT_P2007_06_CUSTOMER_ID_FKEY;
	public static final ForeignKey<PaymentP2007_06Record, StaffRecord> PAYMENT_P2007_06__PAYMENT_P2007_06_STAFF_ID_FKEY = ForeignKeys0.PAYMENT_P2007_06__PAYMENT_P2007_06_STAFF_ID_FKEY;
	public static final ForeignKey<PaymentP2007_06Record, RentalRecord> PAYMENT_P2007_06__PAYMENT_P2007_06_RENTAL_ID_FKEY = ForeignKeys0.PAYMENT_P2007_06__PAYMENT_P2007_06_RENTAL_ID_FKEY;
	public static final ForeignKey<RentalRecord, InventoryRecord> RENTAL__RENTAL_INVENTORY_ID_FKEY = ForeignKeys0.RENTAL__RENTAL_INVENTORY_ID_FKEY;
	public static final ForeignKey<RentalRecord, CustomerRecord> RENTAL__RENTAL_CUSTOMER_ID_FKEY = ForeignKeys0.RENTAL__RENTAL_CUSTOMER_ID_FKEY;
	public static final ForeignKey<RentalRecord, StaffRecord> RENTAL__RENTAL_STAFF_ID_FKEY = ForeignKeys0.RENTAL__RENTAL_STAFF_ID_FKEY;
	public static final ForeignKey<StaffRecord, AddressRecord> STAFF__STAFF_ADDRESS_ID_FKEY = ForeignKeys0.STAFF__STAFF_ADDRESS_ID_FKEY;
	public static final ForeignKey<StaffRecord, StoreRecord> STAFF__STAFF_STORE_ID_FKEY = ForeignKeys0.STAFF__STAFF_STORE_ID_FKEY;
	public static final ForeignKey<StoreRecord, StaffRecord> STORE__STORE_MANAGER_STAFF_ID_FKEY = ForeignKeys0.STORE__STORE_MANAGER_STAFF_ID_FKEY;
	public static final ForeignKey<StoreRecord, AddressRecord> STORE__STORE_ADDRESS_ID_FKEY = ForeignKeys0.STORE__STORE_ADDRESS_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<ActorRecord, Integer> IDENTITY_ACTOR = createIdentity(Actor.ACTOR, Actor.ACTOR.ACTOR_ID);
		public static Identity<AddressRecord, Integer> IDENTITY_ADDRESS = createIdentity(Address.ADDRESS, Address.ADDRESS.ADDRESS_ID);
		public static Identity<CategoryRecord, Integer> IDENTITY_CATEGORY = createIdentity(Category.CATEGORY, Category.CATEGORY.CATEGORY_ID);
		public static Identity<CityRecord, Integer> IDENTITY_CITY = createIdentity(City.CITY, City.CITY.CITY_ID);
		public static Identity<CountryRecord, Integer> IDENTITY_COUNTRY = createIdentity(Country.COUNTRY, Country.COUNTRY.COUNTRY_ID);
		public static Identity<CustomerRecord, Integer> IDENTITY_CUSTOMER = createIdentity(Customer.CUSTOMER, Customer.CUSTOMER.CUSTOMER_ID);
		public static Identity<FilmRecord, Integer> IDENTITY_FILM = createIdentity(Film.FILM, Film.FILM.FILM_ID);
		public static Identity<InventoryRecord, Integer> IDENTITY_INVENTORY = createIdentity(Inventory.INVENTORY, Inventory.INVENTORY.INVENTORY_ID);
		public static Identity<LanguageRecord, Integer> IDENTITY_LANGUAGE = createIdentity(Language.LANGUAGE, Language.LANGUAGE.LANGUAGE_ID);
		public static Identity<PaymentRecord, Integer> IDENTITY_PAYMENT = createIdentity(Payment.PAYMENT, Payment.PAYMENT.PAYMENT_ID);
		public static Identity<PaymentP2007_01Record, Integer> IDENTITY_PAYMENT_P2007_01 = createIdentity(PaymentP2007_01.PAYMENT_P2007_01, PaymentP2007_01.PAYMENT_P2007_01.PAYMENT_ID);
		public static Identity<PaymentP2007_02Record, Integer> IDENTITY_PAYMENT_P2007_02 = createIdentity(PaymentP2007_02.PAYMENT_P2007_02, PaymentP2007_02.PAYMENT_P2007_02.PAYMENT_ID);
		public static Identity<PaymentP2007_03Record, Integer> IDENTITY_PAYMENT_P2007_03 = createIdentity(PaymentP2007_03.PAYMENT_P2007_03, PaymentP2007_03.PAYMENT_P2007_03.PAYMENT_ID);
		public static Identity<PaymentP2007_04Record, Integer> IDENTITY_PAYMENT_P2007_04 = createIdentity(PaymentP2007_04.PAYMENT_P2007_04, PaymentP2007_04.PAYMENT_P2007_04.PAYMENT_ID);
		public static Identity<PaymentP2007_05Record, Integer> IDENTITY_PAYMENT_P2007_05 = createIdentity(PaymentP2007_05.PAYMENT_P2007_05, PaymentP2007_05.PAYMENT_P2007_05.PAYMENT_ID);
		public static Identity<PaymentP2007_06Record, Integer> IDENTITY_PAYMENT_P2007_06 = createIdentity(PaymentP2007_06.PAYMENT_P2007_06, PaymentP2007_06.PAYMENT_P2007_06.PAYMENT_ID);
		public static Identity<RentalRecord, Integer> IDENTITY_RENTAL = createIdentity(Rental.RENTAL, Rental.RENTAL.RENTAL_ID);
		public static Identity<RewardsReportRecord, Integer> IDENTITY_REWARDS_REPORT = createIdentity(RewardsReport.REWARDS_REPORT, RewardsReport.REWARDS_REPORT.CUSTOMER_ID);
		public static Identity<StaffRecord, Integer> IDENTITY_STAFF = createIdentity(Staff.STAFF, Staff.STAFF.STAFF_ID);
		public static Identity<StoreRecord, Integer> IDENTITY_STORE = createIdentity(Store.STORE, Store.STORE.STORE_ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<ActorRecord> ACTOR_PKEY = createUniqueKey(Actor.ACTOR, Actor.ACTOR.ACTOR_ID);
		public static final UniqueKey<AddressRecord> ADDRESS_PKEY = createUniqueKey(Address.ADDRESS, Address.ADDRESS.ADDRESS_ID);
		public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = createUniqueKey(Category.CATEGORY, Category.CATEGORY.CATEGORY_ID);
		public static final UniqueKey<CityRecord> CITY_PKEY = createUniqueKey(City.CITY, City.CITY.CITY_ID);
		public static final UniqueKey<CountryRecord> COUNTRY_PKEY = createUniqueKey(Country.COUNTRY, Country.COUNTRY.COUNTRY_ID);
		public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = createUniqueKey(Customer.CUSTOMER, Customer.CUSTOMER.CUSTOMER_ID);
		public static final UniqueKey<FilmRecord> FILM_PKEY = createUniqueKey(Film.FILM, Film.FILM.FILM_ID);
		public static final UniqueKey<FilmActorRecord> FILM_ACTOR_PKEY = createUniqueKey(FilmActor.FILM_ACTOR, FilmActor.FILM_ACTOR.ACTOR_ID, FilmActor.FILM_ACTOR.FILM_ID);
		public static final UniqueKey<FilmCategoryRecord> FILM_CATEGORY_PKEY = createUniqueKey(FilmCategory.FILM_CATEGORY, FilmCategory.FILM_CATEGORY.FILM_ID, FilmCategory.FILM_CATEGORY.CATEGORY_ID);
		public static final UniqueKey<InventoryRecord> INVENTORY_PKEY = createUniqueKey(Inventory.INVENTORY, Inventory.INVENTORY.INVENTORY_ID);
		public static final UniqueKey<LanguageRecord> LANGUAGE_PKEY = createUniqueKey(Language.LANGUAGE, Language.LANGUAGE.LANGUAGE_ID);
		public static final UniqueKey<PaymentRecord> PAYMENT_PKEY = createUniqueKey(Payment.PAYMENT, Payment.PAYMENT.PAYMENT_ID);
		public static final UniqueKey<RentalRecord> RENTAL_PKEY = createUniqueKey(Rental.RENTAL, Rental.RENTAL.RENTAL_ID);
		public static final UniqueKey<StaffRecord> STAFF_PKEY = createUniqueKey(Staff.STAFF, Staff.STAFF.STAFF_ID);
		public static final UniqueKey<StoreRecord> STORE_PKEY = createUniqueKey(Store.STORE, Store.STORE.STORE_ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AddressRecord, CityRecord> ADDRESS__ADDRESS_CITY_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CITY_PKEY, Address.ADDRESS, Address.ADDRESS.CITY_ID);
		public static final ForeignKey<CityRecord, CountryRecord> CITY__CITY_COUNTRY_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.COUNTRY_PKEY, City.CITY, City.CITY.COUNTRY_ID);
		public static final ForeignKey<CustomerRecord, StoreRecord> CUSTOMER__CUSTOMER_STORE_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STORE_PKEY, Customer.CUSTOMER, Customer.CUSTOMER.STORE_ID);
		public static final ForeignKey<CustomerRecord, AddressRecord> CUSTOMER__CUSTOMER_ADDRESS_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.ADDRESS_PKEY, Customer.CUSTOMER, Customer.CUSTOMER.ADDRESS_ID);
		public static final ForeignKey<FilmRecord, LanguageRecord> FILM__FILM_LANGUAGE_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.LANGUAGE_PKEY, Film.FILM, Film.FILM.LANGUAGE_ID);
		public static final ForeignKey<FilmRecord, LanguageRecord> FILM__FILM_ORIGINAL_LANGUAGE_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.LANGUAGE_PKEY, Film.FILM, Film.FILM.ORIGINAL_LANGUAGE_ID);
		public static final ForeignKey<FilmActorRecord, ActorRecord> FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.ACTOR_PKEY, FilmActor.FILM_ACTOR, FilmActor.FILM_ACTOR.ACTOR_ID);
		public static final ForeignKey<FilmActorRecord, FilmRecord> FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.FILM_PKEY, FilmActor.FILM_ACTOR, FilmActor.FILM_ACTOR.FILM_ID);
		public static final ForeignKey<FilmCategoryRecord, FilmRecord> FILM_CATEGORY__FILM_CATEGORY_FILM_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.FILM_PKEY, FilmCategory.FILM_CATEGORY, FilmCategory.FILM_CATEGORY.FILM_ID);
		public static final ForeignKey<FilmCategoryRecord, CategoryRecord> FILM_CATEGORY__FILM_CATEGORY_CATEGORY_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CATEGORY_PKEY, FilmCategory.FILM_CATEGORY, FilmCategory.FILM_CATEGORY.CATEGORY_ID);
		public static final ForeignKey<InventoryRecord, FilmRecord> INVENTORY__INVENTORY_FILM_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.FILM_PKEY, Inventory.INVENTORY, Inventory.INVENTORY.FILM_ID);
		public static final ForeignKey<InventoryRecord, StoreRecord> INVENTORY__INVENTORY_STORE_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STORE_PKEY, Inventory.INVENTORY, Inventory.INVENTORY.STORE_ID);
		public static final ForeignKey<PaymentRecord, CustomerRecord> PAYMENT__PAYMENT_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, Payment.PAYMENT, Payment.PAYMENT.CUSTOMER_ID);
		public static final ForeignKey<PaymentRecord, StaffRecord> PAYMENT__PAYMENT_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, Payment.PAYMENT, Payment.PAYMENT.STAFF_ID);
		public static final ForeignKey<PaymentRecord, RentalRecord> PAYMENT__PAYMENT_RENTAL_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.RENTAL_PKEY, Payment.PAYMENT, Payment.PAYMENT.RENTAL_ID);
		public static final ForeignKey<PaymentP2007_01Record, CustomerRecord> PAYMENT_P2007_01__PAYMENT_P2007_01_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, PaymentP2007_01.PAYMENT_P2007_01, PaymentP2007_01.PAYMENT_P2007_01.CUSTOMER_ID);
		public static final ForeignKey<PaymentP2007_01Record, StaffRecord> PAYMENT_P2007_01__PAYMENT_P2007_01_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, PaymentP2007_01.PAYMENT_P2007_01, PaymentP2007_01.PAYMENT_P2007_01.STAFF_ID);
		public static final ForeignKey<PaymentP2007_01Record, RentalRecord> PAYMENT_P2007_01__PAYMENT_P2007_01_RENTAL_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.RENTAL_PKEY, PaymentP2007_01.PAYMENT_P2007_01, PaymentP2007_01.PAYMENT_P2007_01.RENTAL_ID);
		public static final ForeignKey<PaymentP2007_02Record, CustomerRecord> PAYMENT_P2007_02__PAYMENT_P2007_02_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, PaymentP2007_02.PAYMENT_P2007_02, PaymentP2007_02.PAYMENT_P2007_02.CUSTOMER_ID);
		public static final ForeignKey<PaymentP2007_02Record, StaffRecord> PAYMENT_P2007_02__PAYMENT_P2007_02_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, PaymentP2007_02.PAYMENT_P2007_02, PaymentP2007_02.PAYMENT_P2007_02.STAFF_ID);
		public static final ForeignKey<PaymentP2007_02Record, RentalRecord> PAYMENT_P2007_02__PAYMENT_P2007_02_RENTAL_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.RENTAL_PKEY, PaymentP2007_02.PAYMENT_P2007_02, PaymentP2007_02.PAYMENT_P2007_02.RENTAL_ID);
		public static final ForeignKey<PaymentP2007_03Record, CustomerRecord> PAYMENT_P2007_03__PAYMENT_P2007_03_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, PaymentP2007_03.PAYMENT_P2007_03, PaymentP2007_03.PAYMENT_P2007_03.CUSTOMER_ID);
		public static final ForeignKey<PaymentP2007_03Record, StaffRecord> PAYMENT_P2007_03__PAYMENT_P2007_03_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, PaymentP2007_03.PAYMENT_P2007_03, PaymentP2007_03.PAYMENT_P2007_03.STAFF_ID);
		public static final ForeignKey<PaymentP2007_03Record, RentalRecord> PAYMENT_P2007_03__PAYMENT_P2007_03_RENTAL_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.RENTAL_PKEY, PaymentP2007_03.PAYMENT_P2007_03, PaymentP2007_03.PAYMENT_P2007_03.RENTAL_ID);
		public static final ForeignKey<PaymentP2007_04Record, CustomerRecord> PAYMENT_P2007_04__PAYMENT_P2007_04_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, PaymentP2007_04.PAYMENT_P2007_04, PaymentP2007_04.PAYMENT_P2007_04.CUSTOMER_ID);
		public static final ForeignKey<PaymentP2007_04Record, StaffRecord> PAYMENT_P2007_04__PAYMENT_P2007_04_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, PaymentP2007_04.PAYMENT_P2007_04, PaymentP2007_04.PAYMENT_P2007_04.STAFF_ID);
		public static final ForeignKey<PaymentP2007_04Record, RentalRecord> PAYMENT_P2007_04__PAYMENT_P2007_04_RENTAL_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.RENTAL_PKEY, PaymentP2007_04.PAYMENT_P2007_04, PaymentP2007_04.PAYMENT_P2007_04.RENTAL_ID);
		public static final ForeignKey<PaymentP2007_05Record, CustomerRecord> PAYMENT_P2007_05__PAYMENT_P2007_05_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, PaymentP2007_05.PAYMENT_P2007_05, PaymentP2007_05.PAYMENT_P2007_05.CUSTOMER_ID);
		public static final ForeignKey<PaymentP2007_05Record, StaffRecord> PAYMENT_P2007_05__PAYMENT_P2007_05_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, PaymentP2007_05.PAYMENT_P2007_05, PaymentP2007_05.PAYMENT_P2007_05.STAFF_ID);
		public static final ForeignKey<PaymentP2007_05Record, RentalRecord> PAYMENT_P2007_05__PAYMENT_P2007_05_RENTAL_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.RENTAL_PKEY, PaymentP2007_05.PAYMENT_P2007_05, PaymentP2007_05.PAYMENT_P2007_05.RENTAL_ID);
		public static final ForeignKey<PaymentP2007_06Record, CustomerRecord> PAYMENT_P2007_06__PAYMENT_P2007_06_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, PaymentP2007_06.PAYMENT_P2007_06, PaymentP2007_06.PAYMENT_P2007_06.CUSTOMER_ID);
		public static final ForeignKey<PaymentP2007_06Record, StaffRecord> PAYMENT_P2007_06__PAYMENT_P2007_06_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, PaymentP2007_06.PAYMENT_P2007_06, PaymentP2007_06.PAYMENT_P2007_06.STAFF_ID);
		public static final ForeignKey<PaymentP2007_06Record, RentalRecord> PAYMENT_P2007_06__PAYMENT_P2007_06_RENTAL_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.RENTAL_PKEY, PaymentP2007_06.PAYMENT_P2007_06, PaymentP2007_06.PAYMENT_P2007_06.RENTAL_ID);
		public static final ForeignKey<RentalRecord, InventoryRecord> RENTAL__RENTAL_INVENTORY_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.INVENTORY_PKEY, Rental.RENTAL, Rental.RENTAL.INVENTORY_ID);
		public static final ForeignKey<RentalRecord, CustomerRecord> RENTAL__RENTAL_CUSTOMER_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.CUSTOMER_PKEY, Rental.RENTAL, Rental.RENTAL.CUSTOMER_ID);
		public static final ForeignKey<RentalRecord, StaffRecord> RENTAL__RENTAL_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, Rental.RENTAL, Rental.RENTAL.STAFF_ID);
		public static final ForeignKey<StaffRecord, AddressRecord> STAFF__STAFF_ADDRESS_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.ADDRESS_PKEY, Staff.STAFF, Staff.STAFF.ADDRESS_ID);
		public static final ForeignKey<StaffRecord, StoreRecord> STAFF__STAFF_STORE_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STORE_PKEY, Staff.STAFF, Staff.STAFF.STORE_ID);
		public static final ForeignKey<StoreRecord, StaffRecord> STORE__STORE_MANAGER_STAFF_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.STAFF_PKEY, Store.STORE, Store.STORE.MANAGER_STAFF_ID);
		public static final ForeignKey<StoreRecord, AddressRecord> STORE__STORE_ADDRESS_ID_FKEY = createForeignKey(mx.ihsa.videoclub.model.Keys.ADDRESS_PKEY, Store.STORE, Store.STORE.ADDRESS_ID);
	}
}
