/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model;


import java.math.BigDecimal;

import javax.annotation.Generated;

import mx.ihsa.videoclub.model.tables.Actor;
import mx.ihsa.videoclub.model.tables.ActorInfo;
import mx.ihsa.videoclub.model.tables.Address;
import mx.ihsa.videoclub.model.tables.Category;
import mx.ihsa.videoclub.model.tables.City;
import mx.ihsa.videoclub.model.tables.Country;
import mx.ihsa.videoclub.model.tables.Customer;
import mx.ihsa.videoclub.model.tables.CustomerList;
import mx.ihsa.videoclub.model.tables.Film;
import mx.ihsa.videoclub.model.tables.FilmActor;
import mx.ihsa.videoclub.model.tables.FilmCategory;
import mx.ihsa.videoclub.model.tables.FilmInStock;
import mx.ihsa.videoclub.model.tables.FilmList;
import mx.ihsa.videoclub.model.tables.FilmNotInStock;
import mx.ihsa.videoclub.model.tables.HistoricoRentas;
import mx.ihsa.videoclub.model.tables.Inventory;
import mx.ihsa.videoclub.model.tables.Language;
import mx.ihsa.videoclub.model.tables.NicerButSlowerFilmList;
import mx.ihsa.videoclub.model.tables.Payment;
import mx.ihsa.videoclub.model.tables.PaymentP2007_01;
import mx.ihsa.videoclub.model.tables.PaymentP2007_02;
import mx.ihsa.videoclub.model.tables.PaymentP2007_03;
import mx.ihsa.videoclub.model.tables.PaymentP2007_04;
import mx.ihsa.videoclub.model.tables.PaymentP2007_05;
import mx.ihsa.videoclub.model.tables.PaymentP2007_06;
import mx.ihsa.videoclub.model.tables.Rental;
import mx.ihsa.videoclub.model.tables.RewardsReport;
import mx.ihsa.videoclub.model.tables.SalesByFilmCategory;
import mx.ihsa.videoclub.model.tables.SalesByStore;
import mx.ihsa.videoclub.model.tables.Staff;
import mx.ihsa.videoclub.model.tables.StaffList;
import mx.ihsa.videoclub.model.tables.Store;

import org.jooq.Field;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.actor
	 */
	public static final Actor ACTOR = mx.ihsa.videoclub.model.tables.Actor.ACTOR;

	/**
	 * The table public.actor_info
	 */
	public static final ActorInfo ACTOR_INFO = mx.ihsa.videoclub.model.tables.ActorInfo.ACTOR_INFO;

	/**
	 * The table public.address
	 */
	public static final Address ADDRESS = mx.ihsa.videoclub.model.tables.Address.ADDRESS;

	/**
	 * The table public.category
	 */
	public static final Category CATEGORY = mx.ihsa.videoclub.model.tables.Category.CATEGORY;

	/**
	 * The table public.city
	 */
	public static final City CITY = mx.ihsa.videoclub.model.tables.City.CITY;

	/**
	 * The table public.country
	 */
	public static final Country COUNTRY = mx.ihsa.videoclub.model.tables.Country.COUNTRY;

	/**
	 * The table public.customer
	 */
	public static final Customer CUSTOMER = mx.ihsa.videoclub.model.tables.Customer.CUSTOMER;

	/**
	 * The table public.customer_list
	 */
	public static final CustomerList CUSTOMER_LIST = mx.ihsa.videoclub.model.tables.CustomerList.CUSTOMER_LIST;

	/**
	 * The table public.film
	 */
	public static final Film FILM = mx.ihsa.videoclub.model.tables.Film.FILM;

	/**
	 * The table public.film_actor
	 */
	public static final FilmActor FILM_ACTOR = mx.ihsa.videoclub.model.tables.FilmActor.FILM_ACTOR;

	/**
	 * The table public.film_category
	 */
	public static final FilmCategory FILM_CATEGORY = mx.ihsa.videoclub.model.tables.FilmCategory.FILM_CATEGORY;

	/**
	 * The table public.film_in_stock
	 */
	public static final FilmInStock FILM_IN_STOCK = mx.ihsa.videoclub.model.tables.FilmInStock.FILM_IN_STOCK;

	/**
	 * Get <code>public.film_in_stock</code> as a field
	 */
	public static FilmInStock FILM_IN_STOCK(Integer pFilmId, Integer pStoreId) {
		return FilmInStock.FILM_IN_STOCK.call(pFilmId, pStoreId);
	}

	/**
	 * Get <code>public.film_in_stock</code> as a field
	 */
	public static FilmInStock FILM_IN_STOCK(Field<Integer> pFilmId, Field<Integer> pStoreId) {
		return FilmInStock.FILM_IN_STOCK.call(pFilmId, pStoreId);
	}

	/**
	 * The table public.film_list
	 */
	public static final FilmList FILM_LIST = mx.ihsa.videoclub.model.tables.FilmList.FILM_LIST;

	/**
	 * The table public.film_not_in_stock
	 */
	public static final FilmNotInStock FILM_NOT_IN_STOCK = mx.ihsa.videoclub.model.tables.FilmNotInStock.FILM_NOT_IN_STOCK;

	/**
	 * Get <code>public.film_not_in_stock</code> as a field
	 */
	public static FilmNotInStock FILM_NOT_IN_STOCK(Integer pFilmId, Integer pStoreId) {
		return FilmNotInStock.FILM_NOT_IN_STOCK.call(pFilmId, pStoreId);
	}

	/**
	 * Get <code>public.film_not_in_stock</code> as a field
	 */
	public static FilmNotInStock FILM_NOT_IN_STOCK(Field<Integer> pFilmId, Field<Integer> pStoreId) {
		return FilmNotInStock.FILM_NOT_IN_STOCK.call(pFilmId, pStoreId);
	}

	/**
	 * The table public.historico_rentas
	 */
	public static final HistoricoRentas HISTORICO_RENTAS = mx.ihsa.videoclub.model.tables.HistoricoRentas.HISTORICO_RENTAS;

	/**
	 * The table public.inventory
	 */
	public static final Inventory INVENTORY = mx.ihsa.videoclub.model.tables.Inventory.INVENTORY;

	/**
	 * The table public.language
	 */
	public static final Language LANGUAGE = mx.ihsa.videoclub.model.tables.Language.LANGUAGE;

	/**
	 * The table public.nicer_but_slower_film_list
	 */
	public static final NicerButSlowerFilmList NICER_BUT_SLOWER_FILM_LIST = mx.ihsa.videoclub.model.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST;

	/**
	 * The table public.payment
	 */
	public static final Payment PAYMENT = mx.ihsa.videoclub.model.tables.Payment.PAYMENT;

	/**
	 * The table public.payment_p2007_01
	 */
	public static final PaymentP2007_01 PAYMENT_P2007_01 = mx.ihsa.videoclub.model.tables.PaymentP2007_01.PAYMENT_P2007_01;

	/**
	 * The table public.payment_p2007_02
	 */
	public static final PaymentP2007_02 PAYMENT_P2007_02 = mx.ihsa.videoclub.model.tables.PaymentP2007_02.PAYMENT_P2007_02;

	/**
	 * The table public.payment_p2007_03
	 */
	public static final PaymentP2007_03 PAYMENT_P2007_03 = mx.ihsa.videoclub.model.tables.PaymentP2007_03.PAYMENT_P2007_03;

	/**
	 * The table public.payment_p2007_04
	 */
	public static final PaymentP2007_04 PAYMENT_P2007_04 = mx.ihsa.videoclub.model.tables.PaymentP2007_04.PAYMENT_P2007_04;

	/**
	 * The table public.payment_p2007_05
	 */
	public static final PaymentP2007_05 PAYMENT_P2007_05 = mx.ihsa.videoclub.model.tables.PaymentP2007_05.PAYMENT_P2007_05;

	/**
	 * The table public.payment_p2007_06
	 */
	public static final PaymentP2007_06 PAYMENT_P2007_06 = mx.ihsa.videoclub.model.tables.PaymentP2007_06.PAYMENT_P2007_06;

	/**
	 * The table public.rental
	 */
	public static final Rental RENTAL = mx.ihsa.videoclub.model.tables.Rental.RENTAL;

	/**
	 * The table public.rewards_report
	 */
	public static final RewardsReport REWARDS_REPORT = mx.ihsa.videoclub.model.tables.RewardsReport.REWARDS_REPORT;

	/**
	 * Get <code>public.rewards_report</code> as a field
	 */
	public static RewardsReport REWARDS_REPORT(Integer minMonthlyPurchases, BigDecimal minDollarAmountPurchased) {
		return RewardsReport.REWARDS_REPORT.call(minMonthlyPurchases, minDollarAmountPurchased);
	}

	/**
	 * Get <code>public.rewards_report</code> as a field
	 */
	public static RewardsReport REWARDS_REPORT(Field<Integer> minMonthlyPurchases, Field<BigDecimal> minDollarAmountPurchased) {
		return RewardsReport.REWARDS_REPORT.call(minMonthlyPurchases, minDollarAmountPurchased);
	}

	/**
	 * The table public.sales_by_film_category
	 */
	public static final SalesByFilmCategory SALES_BY_FILM_CATEGORY = mx.ihsa.videoclub.model.tables.SalesByFilmCategory.SALES_BY_FILM_CATEGORY;

	/**
	 * The table public.sales_by_store
	 */
	public static final SalesByStore SALES_BY_STORE = mx.ihsa.videoclub.model.tables.SalesByStore.SALES_BY_STORE;

	/**
	 * The table public.staff
	 */
	public static final Staff STAFF = mx.ihsa.videoclub.model.tables.Staff.STAFF;

	/**
	 * The table public.staff_list
	 */
	public static final StaffList STAFF_LIST = mx.ihsa.videoclub.model.tables.StaffList.STAFF_LIST;

	/**
	 * The table public.store
	 */
	public static final Store STORE = mx.ihsa.videoclub.model.tables.Store.STORE;
}
