/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Keys;
import mx.ihsa.videoclub.model.Public;
import mx.ihsa.videoclub.model.tables.records.CityRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City extends TableImpl<CityRecord> {

	private static final long serialVersionUID = -2051017186;

	/**
	 * The reference instance of <code>public.city</code>
	 */
	public static final City CITY = new City();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CityRecord> getRecordType() {
		return CityRecord.class;
	}

	/**
	 * The column <code>public.city.city_id</code>.
	 */
	public final TableField<CityRecord, Integer> CITY_ID = createField("city_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.city.city</code>.
	 */
	public final TableField<CityRecord, String> CITY_ = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.city.country_id</code>.
	 */
	public final TableField<CityRecord, Short> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.city.last_update</code>.
	 */
	public final TableField<CityRecord, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.city</code> table reference
	 */
	public City() {
		this("city", null);
	}

	/**
	 * Create an aliased <code>public.city</code> table reference
	 */
	public City(String alias) {
		this(alias, CITY);
	}

	private City(String alias, Table<CityRecord> aliased) {
		this(alias, aliased, null);
	}

	private City(String alias, Table<CityRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CityRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CityRecord> getPrimaryKey() {
		return Keys.CITY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CityRecord>> getKeys() {
		return Arrays.<UniqueKey<CityRecord>>asList(Keys.CITY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<CityRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<CityRecord, ?>>asList(Keys.CITY__CITY_COUNTRY_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public City as(String alias) {
		return new City(alias, this);
	}

	/**
	 * Rename this table
	 */
	public City rename(String name) {
		return new City(name, null);
	}
}
