/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables;


import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Public;
import mx.ihsa.videoclub.model.tables.records.FilmInStockRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmInStock extends TableImpl<FilmInStockRecord> {

	private static final long serialVersionUID = 1401224262;

	/**
	 * The reference instance of <code>public.film_in_stock</code>
	 */
	public static final FilmInStock FILM_IN_STOCK = new FilmInStock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FilmInStockRecord> getRecordType() {
		return FilmInStockRecord.class;
	}

	/**
	 * The column <code>public.film_in_stock.p_film_count</code>.
	 */
	public final TableField<FilmInStockRecord, Integer> P_FILM_COUNT = createField("p_film_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.film_in_stock</code> table reference
	 */
	public FilmInStock() {
		this("film_in_stock", null);
	}

	/**
	 * Create an aliased <code>public.film_in_stock</code> table reference
	 */
	public FilmInStock(String alias) {
		this(alias, FILM_IN_STOCK);
	}

	private FilmInStock(String alias, Table<FilmInStockRecord> aliased) {
		this(alias, aliased, new Field[2]);
	}

	private FilmInStock(String alias, Table<FilmInStockRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmInStock as(String alias) {
		return new FilmInStock(alias, this, parameters);
	}

	/**
	 * Rename this table
	 */
	public FilmInStock rename(String name) {
		return new FilmInStock(name, null, parameters);
	}

	/**
	 * Call this table-valued function
	 */
	public FilmInStock call(Integer pFilmId, Integer pStoreId) {
		return new FilmInStock(getName(), null, new Field[] { DSL.val(pFilmId), DSL.val(pStoreId) });
	}

	/**
	 * Call this table-valued function
	 */
	public FilmInStock call(Field<Integer> pFilmId, Field<Integer> pStoreId) {
		return new FilmInStock(getName(), null, new Field[] { pFilmId, pStoreId });
	}
}
