/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables;


import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Public;
import mx.ihsa.videoclub.model.tables.records.FilmNotInStockRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmNotInStock extends TableImpl<FilmNotInStockRecord> {

	private static final long serialVersionUID = 2094985058;

	/**
	 * The reference instance of <code>public.film_not_in_stock</code>
	 */
	public static final FilmNotInStock FILM_NOT_IN_STOCK = new FilmNotInStock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FilmNotInStockRecord> getRecordType() {
		return FilmNotInStockRecord.class;
	}

	/**
	 * The column <code>public.film_not_in_stock.p_film_count</code>.
	 */
	public final TableField<FilmNotInStockRecord, Integer> P_FILM_COUNT = createField("p_film_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.film_not_in_stock</code> table reference
	 */
	public FilmNotInStock() {
		this("film_not_in_stock", null);
	}

	/**
	 * Create an aliased <code>public.film_not_in_stock</code> table reference
	 */
	public FilmNotInStock(String alias) {
		this(alias, FILM_NOT_IN_STOCK);
	}

	private FilmNotInStock(String alias, Table<FilmNotInStockRecord> aliased) {
		this(alias, aliased, new Field[2]);
	}

	private FilmNotInStock(String alias, Table<FilmNotInStockRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmNotInStock as(String alias) {
		return new FilmNotInStock(alias, this, parameters);
	}

	/**
	 * Rename this table
	 */
	public FilmNotInStock rename(String name) {
		return new FilmNotInStock(name, null, parameters);
	}

	/**
	 * Call this table-valued function
	 */
	public FilmNotInStock call(Integer pFilmId, Integer pStoreId) {
		return new FilmNotInStock(getName(), null, new Field[] { DSL.val(pFilmId), DSL.val(pStoreId) });
	}

	/**
	 * Call this table-valued function
	 */
	public FilmNotInStock call(Field<Integer> pFilmId, Field<Integer> pStoreId) {
		return new FilmNotInStock(getName(), null, new Field[] { pFilmId, pStoreId });
	}
}
