/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Keys;
import mx.ihsa.videoclub.model.Public;
import mx.ihsa.videoclub.model.tables.records.FilmActorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmActor extends TableImpl<FilmActorRecord> {

	private static final long serialVersionUID = -1004027265;

	/**
	 * The reference instance of <code>public.film_actor</code>
	 */
	public static final FilmActor FILM_ACTOR = new FilmActor();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FilmActorRecord> getRecordType() {
		return FilmActorRecord.class;
	}

	/**
	 * The column <code>public.film_actor.actor_id</code>.
	 */
	public final TableField<FilmActorRecord, Short> ACTOR_ID = createField("actor_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.film_actor.film_id</code>.
	 */
	public final TableField<FilmActorRecord, Short> FILM_ID = createField("film_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.film_actor.last_update</code>.
	 */
	public final TableField<FilmActorRecord, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.film_actor</code> table reference
	 */
	public FilmActor() {
		this("film_actor", null);
	}

	/**
	 * Create an aliased <code>public.film_actor</code> table reference
	 */
	public FilmActor(String alias) {
		this(alias, FILM_ACTOR);
	}

	private FilmActor(String alias, Table<FilmActorRecord> aliased) {
		this(alias, aliased, null);
	}

	private FilmActor(String alias, Table<FilmActorRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FilmActorRecord> getPrimaryKey() {
		return Keys.FILM_ACTOR_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FilmActorRecord>> getKeys() {
		return Arrays.<UniqueKey<FilmActorRecord>>asList(Keys.FILM_ACTOR_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<FilmActorRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<FilmActorRecord, ?>>asList(Keys.FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY, Keys.FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FilmActor as(String alias) {
		return new FilmActor(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FilmActor rename(String name) {
		return new FilmActor(name, null);
	}
}
