/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Keys;
import mx.ihsa.videoclub.model.Public;
import mx.ihsa.videoclub.model.tables.records.LanguageRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language extends TableImpl<LanguageRecord> {

	private static final long serialVersionUID = -1020592756;

	/**
	 * The reference instance of <code>public.language</code>
	 */
	public static final Language LANGUAGE = new Language();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LanguageRecord> getRecordType() {
		return LanguageRecord.class;
	}

	/**
	 * The column <code>public.language.language_id</code>.
	 */
	public final TableField<LanguageRecord, Integer> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.language.name</code>.
	 */
	public final TableField<LanguageRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>public.language.last_update</code>.
	 */
	public final TableField<LanguageRecord, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.language</code> table reference
	 */
	public Language() {
		this("language", null);
	}

	/**
	 * Create an aliased <code>public.language</code> table reference
	 */
	public Language(String alias) {
		this(alias, LANGUAGE);
	}

	private Language(String alias, Table<LanguageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Language(String alias, Table<LanguageRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<LanguageRecord, Integer> getIdentity() {
		return Keys.IDENTITY_LANGUAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<LanguageRecord> getPrimaryKey() {
		return Keys.LANGUAGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<LanguageRecord>> getKeys() {
		return Arrays.<UniqueKey<LanguageRecord>>asList(Keys.LANGUAGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Language as(String alias) {
		return new Language(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Language rename(String name) {
		return new Language(name, null);
	}
}
