/**
 * This class is generated by jOOQ
 */
package mx.ihsa.videoclub.model.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import mx.ihsa.videoclub.model.Keys;
import mx.ihsa.videoclub.model.Public;
import mx.ihsa.videoclub.model.tables.records.PaymentP2007_04Record;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentP2007_04 extends TableImpl<PaymentP2007_04Record> {

	private static final long serialVersionUID = -430080931;

	/**
	 * The reference instance of <code>public.payment_p2007_04</code>
	 */
	public static final PaymentP2007_04 PAYMENT_P2007_04 = new PaymentP2007_04();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PaymentP2007_04Record> getRecordType() {
		return PaymentP2007_04Record.class;
	}

	/**
	 * The column <code>public.payment_p2007_04.payment_id</code>.
	 */
	public final TableField<PaymentP2007_04Record, Integer> PAYMENT_ID = createField("payment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.payment_p2007_04.customer_id</code>.
	 */
	public final TableField<PaymentP2007_04Record, Short> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.payment_p2007_04.staff_id</code>.
	 */
	public final TableField<PaymentP2007_04Record, Short> STAFF_ID = createField("staff_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.payment_p2007_04.rental_id</code>.
	 */
	public final TableField<PaymentP2007_04Record, Integer> RENTAL_ID = createField("rental_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.payment_p2007_04.amount</code>.
	 */
	public final TableField<PaymentP2007_04Record, BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.NUMERIC.precision(5, 2).nullable(false), this, "");

	/**
	 * The column <code>public.payment_p2007_04.payment_date</code>.
	 */
	public final TableField<PaymentP2007_04Record, Timestamp> PAYMENT_DATE = createField("payment_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>public.payment_p2007_04</code> table reference
	 */
	public PaymentP2007_04() {
		this("payment_p2007_04", null);
	}

	/**
	 * Create an aliased <code>public.payment_p2007_04</code> table reference
	 */
	public PaymentP2007_04(String alias) {
		this(alias, PAYMENT_P2007_04);
	}

	private PaymentP2007_04(String alias, Table<PaymentP2007_04Record> aliased) {
		this(alias, aliased, null);
	}

	private PaymentP2007_04(String alias, Table<PaymentP2007_04Record> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PaymentP2007_04Record, Integer> getIdentity() {
		return Keys.IDENTITY_PAYMENT_P2007_04;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PaymentP2007_04Record, ?>> getReferences() {
		return Arrays.<ForeignKey<PaymentP2007_04Record, ?>>asList(Keys.PAYMENT_P2007_04__PAYMENT_P2007_04_CUSTOMER_ID_FKEY, Keys.PAYMENT_P2007_04__PAYMENT_P2007_04_STAFF_ID_FKEY, Keys.PAYMENT_P2007_04__PAYMENT_P2007_04_RENTAL_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentP2007_04 as(String alias) {
		return new PaymentP2007_04(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PaymentP2007_04 rename(String name) {
		return new PaymentP2007_04(name, null);
	}
}
